[package]
name = "cpal-tests"
version = "0.1.0"
authors = ["Thibaut REMY <thibaut@thibaut.re>"]

[dependencies]
cpal = "0.8.2"
rand = "0.5.5"
tokio = "0.1.8"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
